# -*- coding: utf-8 -*-
{
    'name': "Account Dashboard Ninja",

    'summary': """
    Account Dashboard Ninja!
    """,

    'description': """
        Dashboard Ninja v13.0,
        Odoo Dashboard, 
        Dashboard,
        Odoo apps,
        Dashboard app,
        HR Dashboard,
        Sales Dashboard, 
        Account Dashboard, 
        inventory Dashboard, 
        Lead Dashboard, 
        Opportunity Dashboard, 
        CRM Dashboard,
        POS,
        POS Dashboard,
        Connectors,
        Web Dynamic,
        Report Import/Export,
        Date Filter,
        HR,
        Sales,
        Theme,
        Tile Dashboard,
        Dashboard Widgets,
        Dashboard Manager,
        Debranding,
        Customize Dashboard,
        Graph Dashboard,
        Charts Dashboard,
        Invoice Dashboard,
        Project management,
        ksolves,
        ksolves apps,
        ksolves india pvt. ltd.,
        Best Accounting Dashboard Apps,
        Accounting Dashboard Apps,
        Interactive accounting management,
        Best Accounting Management Dashboard Apps,
        Accounting Management Dashboard Apps,
        Accounting Dashboard Apps,
        Income Management Dashboard Apps,
        Best Accounting Management Dashboard Apps,
        Dashboards,
        Purchase Invoice,
        Bank Balance Dashboard,
        Invoice Dashboards,
        Accounting Management System,
        Finance Management System,
        Purchase Order Dashboards,
        Sales Order Dashboards,
        Accounting Alert Apps,
        Expense Alert Apps,
        Visualization charts,
        Finance Dashboard,
        Best Dashboard Apps,
        Accounting Age Report,
        Accounting Report, 
        Accounting Valuation,
        Accounting Quantities,
        Stock per Location,
        Top selling items Dashboard,
        Odoo Dashboard,
        Dashboard for Odoo,
        Accounting Tracker Apps,
        Accounting Tracking Apps,
        Finance Tracker Apps,
        Business Tracker Apps, 
        Accounting Metrics,
        Expense Dashboard Apps,
        Invoicing Dashboard,
        Vendor Payable Report,
        Executive Sale Returns,
        Top Sale Revenue Customer,
    """,

    'author': "Ksolves India Pvt. Ltd.",
    'license': 'OPL-1',
    'currency': 'EUR',
    'price': 0.0,
    'website': "https://www.ksolves.com",
    'maintainer': 'Ksolves India Pvt. Ltd.',
    'live_test_url': 'https://dashboardninja.kappso.com/web/demo_login',
    'category': 'Tools',
    'support': 'sales@ksolves.com',
    'version': '1.0.0',
    'images': ['static/description/banner.png'],

    'depends': ['ks_dashboard_ninja', 'account'],

    'data': [
        'data/ks_account_data.xml',
    ],
}
